### PR TITLE
added findbug and checkstyle support while building

### PR DESCRIPTION
**Pull request by ameyjadiye**

### CODE REVIEW

**Comment by ameyjadiye** [comment]
@PascalSchumacher , can you take a look at this ? seems only issue with findbug on  java6 build, rest seems Ok.

**Comment by PascalSchumacher** [comment]
The findbugs version used is not java 6 compatible.

**Comment by ameyjadiye** [comment]
@chtompki , is this not accepted ?

**Comment by chtompki** [comment]
Oh pardon. I misread. I’ll re-run through it.

**Comment by PascalSchumacher** [comment]
As I said before this can not be merged as it is, because it fails on java 6.

The simple fix of just downgrading the findbugs version can not be applied, because 2.x versions do not work on java 8. A possible solution would be to create a java 6 profile which detects java 6 and with uses the java 6 compatible maven-findbugs-plugin version 2.x.

**Comment by PascalSchumacher** [comment]
Thanks!

I solved the findbugs version problem with: https://github.com/apache/commons-cli/commit/2392ae8afc08b496a3eb49908aa421ea86a9679e

**Comment by ameyjadiye** [comment]
Thanks @PascalSchumacher

**Pull request closed without merging**
