### PR TITLE
Refactor default parser test

### PR DESCRIPTION
**Pull request by sigee**
- Satisfy the TODO comment
- Fill out the missing cases
  - Long option quote handling DEFAULT behavior
  - Short option quote handling DEFAULT behavior
  - Short option concatenated quote handling WITH strip
  - Short option concatenated quote handling WITHOUT strip

### CODE REVIEW

**Comment by garydgregory** [comment]
This PR has an empty description. Please tell us what this fixes.

**Comment by sigee** [comment]
The main purpose was to satisfy the TODO comment in the code. "TODO Needs a rework using JUnit parameterized tests."
While moving the test cases into the argument provider, I also filled out some missing cases, because in the provider it is more conspicuous which cases are covered and which are not.
Unfortunatelly the parent abstract class also requires a refactor, to eliminate the two disabled inherrited test cases, because their behavior differs from the other parsers, but could be covered by the parameterized test.

**Comment by garydgregory** [comment]
@sigee 
Thank you for your PR.
Please run `mvn` before you push and fix any build failures.

**Comment by sigee** [comment]
@garydgregory 
I usually do run verification at least before the pull request, but this time I missed it for some reason I couldn't remember.
Anyway, I fixed the checkstyle issues.
I also add a small fix for the date related test cases, because in my local system the date format was a bit different and those 3 cases were broken. Now they are not locale dependent.

**Comment by garydgregory** [comment]
@sigee 
Merged; TY!

**Pull request merged**
