### PR TITLE
Assignment

### PR DESCRIPTION
**Pull request by dhruvdk7**

### CODE REVIEW

**Comment by garydgregory** [comment]
@dhruvdk7 
This PR has no description and its title is meaningless. What are you trying to do?

**Comment by dhruvdk7** [comment]
Hey there.....Sorry for the inconvenience

There were design smells in the code. I identified 3 implementation smells
and 2 design smell. For the move method Refractoring I have removed the
feature envy smell . It was 13 earlier and now it is 12.


Awaiting for your reply,

Dhruv Kothari

**Review by garydgregory — CHANGES_REQUESTED** [review]
You can't remove public or protected code as it will break binary compatibility. Java type names start with a capital letter.

**Comment by garydgregory** [comment]
Closing: No reply.

**Pull request closed without merging**
