### PR TITLE
[CLI-312] Illustrate inconsistent behaviour in key/value pairs (Java property style)

### PR DESCRIPTION
**Pull request by mthmulders**

### CODE REVIEW

**Comment by garydgregory** [comment]
@mthmulders 
Please fix the build or close this PR.

**Comment by garydgregory** [comment]
Hello @mthmulders 
Do you have a suggestion for a fix?

**Comment by mthmulders** [comment]
> Hello @mthmulders Do you have a suggestion for a fix?

Nope, I haven't. The issue was discovered while working on [MNG-7217](https://issues.apache.org/jira/browse/MNG-7217), but we decided not to address it in Maven.

**Comment by garydgregory** [comment]
> > Hello @mthmulders Do you have a suggestion for a fix?
> 
> Nope, I haven't. The issue was discovered while working on [MNG-7217](https://issues.apache.org/jira/browse/MNG-7217), but we decided not to address it in Maven.

k, thank you for the update @mthmulders

**Pull request closed without merging**
