### PR TITLE
Change method visibility

### PR DESCRIPTION
**Pull request by chingjustwe**
Change the visibility of method `handleUnknownToken()` to `protected`, give end engineer a change to handle such case themselves (I just need to ignore the exception `ParseException` here 😃).

> Since I do not find the **Issues** tab to raise an issue, so I just created a PR myself, thanks.

### CODE REVIEW

**Comment by garydgregory** [comment]
@chingjustwe 
Thank you for your PR. You should provide a test that showcases this use case to make sure it's the best path forward.

**Comment by garydgregory** [comment]
@chingjustwe ping

**Comment by chingjustwe** [comment]
@garydgregory sorry for late reply...the use case for us is:
There is a monitoring platform, which allows users to provide their own java plugins to run some checks, we use `apache-commons-cli` to parse the input parameters, such as `--param1 "value1" --param2 "value2"`. We need to have the torrent to let users input unrecognized parameters, like `--param1 "value1" -oops "unrecognized" --param2 "value2"`, what we want here is just leave a warning message (unrecognized parameter "oops") and proceed. Changing the visibility of method `handleUnknownToken()` would give us such a chance to do it.

**Comment by garydgregory** [comment]
Then an example as a test would be beneficial.

**Comment by garydgregory** [comment]
Closing: No reply.

**Pull request closed without merging**
