### PR TITLE
Try to fix problem on Travis CI with JDK6

### PR DESCRIPTION
**Pull request by britter**
See https://github.com/travis-ci/travis-ci/issues/9713

### CODE REVIEW

**Comment by kinow** [comment]
Oh, Travis is still unhappy. But good to know it's not supporting JDK6 out of the box any longer

**Comment by garydgregory** [comment]
Let's drop Java 6 support.

Gary

**Comment by britter** [comment]
@kinow we will probably have to build the build matrix ourself without the `jdk` if we want to support java 6.

**Comment by kinow** [comment]
I stopped using Java 6 long time ago, so I'd be +1 for that. But probably better to check at the dev-list @garydgregory I think (can't recall if Tomcat or some other project used cli too?)

**Comment by garydgregory** [comment]
On Sun, Feb 10, 2019 at 7:01 AM Bruno P. Kinoshita <notifications@github.com>
wrote:

> I stopped using Java 6 long time ago, so I'd be +1 for that. But probably
> better to check at the dev-list @garydgregory
> <https://github.com/garydgregory> I think (can't recall if Tomcat or some
> other project used cli too?)
>
No one would force them to upgrade...

Gary

**Pull request closed without merging**
