### PR TITLE
Fixes for CLI-321

### PR DESCRIPTION
**Pull request by Claudenw**
Adds BeanUtils dependency to POM and implements TypeHandler using the BeanUtils classes.

Handles all methods that were in the original TypeHandler as well as other default classes provided by BeanUtils. Test updated to show proper parsing of types that previously were not implemented.

Includes new cli.converters package that may be better handled by BeanUtils as it moves forward to support FunctionalInterfaces.

### CODE REVIEW

**Comment by Claudenw** [comment]
This is still a draft.

**Comment by garydgregory** [comment]
I doubt we want to add a dependency on anything for Commons CLI, especially for what was meant to be a lightweight library. This would add Commons BeanUtils, Commons Logging, Commons Collections, and Commons Lang. It's a lot compared to JCommander and picocli...

**Comment by Claudenw** [comment]
Added getParsedOptionValue methods with default values.  Switched to ConvertUtilsBean2 for conversions.

**Comment by Claudenw** [comment]
@garydgregory The code note was there and there is a lot of work in BeanUtils to make the conversions work cleanly.  Might it be reasonable to make the dependency Optional so that if there is a wish to do BeanUtils (and other classes) are added,  but for most cases it is not?

**Comment by garydgregory** [comment]
Hello @Claudenw 
Let's see what other folks think.

**Comment by Claudenw** [comment]
Reworked without BeanUtils as pull #216 I think that is a better solution.  Will move forward with whichever version the community is happiest with.

**Comment by Claudenw** [comment]
Closed in favor of #216

**Pull request closed without merging**
